apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbg
  template:
    metadata:
      labels:
        app: dbg
    spec:
      containers:
        - name: dbg
#          image: dbg:0.2
          image: ysedcoupa/dbg:latest
#          image: gcr.io/google-samples/hello-app:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 30123


