apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-k8s-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbg
  template:
    metadata:
      labels:
        app: dbg
    spec:
      containers:
        - name: dbg
          image: ysedcoupa/dbg:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 30123


